FROM nginx:1.12.2

# Add application files
ADD ./client/dist/client /var/www/htdocs
ADD ./client/nginx/nginx.conf /etc/nginx/nginx.conf 
ADD ./client/nginx/site-prod.conf /etc/nginx/conf.d/default.conf 

RUN touch /var/run/nginx.pid && \
    chown -R www-data: /etc/nginx/ && \
    chown -R www-data: /var/run/nginx.pid && \
    chown -R www-data: /var/cache/nginx && \
    chown -R www-data: /var/www/htdocs

USER www-data

#Expose the port
EXPOSE 8080

STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]